arb-dir: l10n
template-arb-file: en.arb
output-localization-file: phone_field_localization.dart
output-class: PhoneFieldLocalization
output-dir: lib/src/localization/generated
synthetic-package: false
format: true
